Repository DuckDuckStudio/GenshinImpact-UP-Search, pull requests merged in 2024-08, with the labels that each got.

#9 feat: 议题表单
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/new_account_request.yml
Labels: 文档

#11 add＋: 新对应
  Search-table.md
Labels: 检查：通过

#12 New Account
  Search-table.md
Labels: 检查：通过, 新对应账号, 审查通过

#13 New Account
  Search-table.md
Labels: 检查：通过, 新对应账号
